services:
  app:
    build: .
    container_name: atividadeavaliativa
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/livrodb
      - SPRING_DATASOURCE_USERNAME=livroappuser
      - SPRING_DATASOURCE_PASSWORD=87654321
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect
    depends_on:
      - db
    command: /wait-for-it.sh db:3306 -- gradle build --no-daemon && java -jar build/libs/atividadeavaliativa.jar

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: livrodb
      MYSQL_USER: livroappuser
      MYSQL_PASSWORD: 87654321
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
